.*-4bit-128g:
  wbits: 4
  groupsize: 128
.*-128g-4bit:
  wbits: 4
  groupsize: 128
llama-[0-9]*b-4bit$:
  wbits: 4
  groupsize: -1
  model_type: 'llama'
.*oasst-sft-1-pythia-12b:
  mode: 'instruct'
  instruction_template: 'Open Assistant'
.*vicuna:
  mode: 'instruct'
  instruction_template: 'Vicuna'
.*alpaca:
  mode: 'instruct'
  instruction_template: 'Alpaca'
